version: '3.8'
services:
  app:
    platform: linux/x86_64
    container_name: service-name
    image: nestjs-service-name
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3333:3333"
    networks:
      - shared-net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  shared-net:
    external: true
